### ISSUE TITLE
Support for ISRC with id 0

### ISSUE THREAD

**Issue by taakberg** [daniel-zahariev/music-codes#2]
Hi there,

I've encountered a case where I tried to handle ISRC `US-BQU-21-00000`, but this failed because this library doesn't consider an ISRC with an ID of 0 to be a valid ISRC.

However, this ISRC is actually used for a recording, see https://isrcsearch.ifpi.org/#!/search?isrcCode=USBQU2100000&tab=lookup&showReleases=0&start=0&number=10

It looks like ISRC's with an ID of 0 are not considered valid on purpose. Is there a reasoning behind this? Or can this be adjusted? If so, I'm willing to create a PR.

Thanks in advance!

**Comment by daniel-zahariev** [comment]
Hi @taakberg,
I'm surprised that someone else is using this library :)
I've just added a new release that should help you work this out. You need to call `treatZeroIdsAsValid` static method on Isrc class.
Let me know if this doesn't work for you.

Regards,
Daniel

**Comment by taakberg** [comment]
I am definitely using it, it's saving me a lot of work. Thanks for this library!

I'll try out the new functionality soon and will let you know if there is anything further. Thanks again!

**Comment by daniel-zahariev** [comment]
hey @taakberg,
out of interest - are you using only the ISRC class or others as well?
Do you have a need for other music related codes? I have some more planned and your feedback might help me prioritise some over others.

Regards

**Comment by taakberg** [comment]
Hi @daniel-zahariev, I'm only using the ISRC one. I'm working on a platform which connects to several music streaming providers (e.g. Spotify, Apple Music, etc). They all seem to use ISRC codes, so that's what I'm using. I wouldn't know what other music related codes might be useful for other users.

**Comment by daniel-zahariev** [comment]
ok, thanks!
