### ISSUE TITLE
How exactly do we include this in our php files?

### ISSUE THREAD

**Issue by adaniel2** [daniel-zahariev/music-codes#3]
I have something like this atm:

require __DIR__ . '/vendor/autoload.php';
use MusicCodes\Isrc;

But I am still unable to use the Isrc class. How should I be going about this?

**Comment by daniel-zahariev** [comment]
The full namespace is different:
```php
<?php 
require __DIR__ . '/vendor/autoload.php';
use DanielZ\MusicCodes\Isrc;

$isrc = new Isrc('GB-A1B-11-00003');
echo $isrc;
```

**Comment by adaniel2** [comment]
Hi, thanks.

I tried this just now and get the following errors:

Undefined namespace 'MusicCodes'
Undefined class 'Isrc'

Should I be doing something in addition to the code provided?

**EDIT**

I was able to clear the errors after reopening the file correctly in my IDE. The .php code was in fact working even prior to clearing the errors, thanks.
